version: 2
updates:
- package-ecosystem: npm
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  commit-message:
    prefix: chore
    include: scope
  reviewers:
  - luth2

- package-ecosystem: npm
  directory: /Fotoupload_page
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
  reviewers:
  - luth2

- package-ecosystem: npm
  directory: /Web_Slideshow
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
  reviewers:
  - luth2

- package-ecosystem: docker
  directory: /Fotoupload_page
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  commit-message:
    prefix: chore
    include: scope
  reviewers:
  - luth2

- package-ecosystem: docker
  directory: /Web_Slideshow
  schedule:
    interval: weekly
  open-pull-requests-limit: 5
  commit-message:
    prefix: chore
    include: scope
  reviewers:
  - luth2

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  commit-message:
    prefix: chore
    include: scope
  reviewers:
  - luth2